# English (United States) translations for glance.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-11-23 06:03+0000\n"
"PO-Revision-Date: 2013-04-10 10:09+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/schema.py:56
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "custom properties (%(props)s) conflict with base properties"

#: glance/api/authorization.py:90 glance/api/authorization.py:101
#, python-format
msgid "You cannot get image member for %s"
msgstr "You cannot get image member for %s"

#: glance/api/authorization.py:109
#, python-format
msgid "You cannot delete image member for %s"
msgstr "You cannot delete image member for %s"

#: glance/api/authorization.py:118
#, python-format
msgid "You cannot add image member for %s"
msgstr "You cannot add image member for %s"

#: glance/api/authorization.py:128
#, python-format
msgid "You cannot update image member %s"
msgstr "You cannot update image member %s"

#: glance/api/authorization.py:147
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "You are not permitted to create images owned by '%s'."

#: glance/api/authorization.py:165
msgid "You are not permitted to create image members for the image."
msgstr "You are not permitted to create image members for the image."

#: glance/api/authorization.py:170 glance/api/authorization.py:306
msgid "Public images do not have members."
msgstr "Public images do not have members."

#: glance/api/authorization.py:185 glance/api/authorization.py:214
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "You are not permitted to modify '%s' on this image."

#: glance/api/authorization.py:193
msgid "You are not permitted to modify locations for this image."
msgstr "You are not permitted to modify locations for this image."

#: glance/api/authorization.py:218
msgid "You are not permitted to modify this image."
msgstr "You are not permitted to modify this image."

#: glance/api/authorization.py:231
msgid "You are not permitted to modify tags on this image."
msgstr "You are not permitted to modify tags on this image."

#: glance/api/authorization.py:270
msgid "You are not permitted to delete this image."
msgstr "You are not permitted to delete this image."

#: glance/api/authorization.py:281
msgid "You are not permitted to upload data for this image."
msgstr "You are not permitted to upload data for this image."

#: glance/api/common.py:44
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"

#: glance/api/common.py:51
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Corrupt image download for image %(image_id)s"

#: glance/api/common.py:82 glance/notifier/__init__.py:194
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "An error occurred during image.send notification: %(err)s"

#: glance/api/policy.py:34
msgid "The location of the policy file."
msgstr "The location of the policy file."

#: glance/api/policy.py:36
msgid "The default policy to use."
msgstr "The default policy to use."

#: glance/api/policy.py:83
#, python-format
msgid "Loaded %(rule_type)spolicy rules: %(text_rules)s"
msgstr "Loaded %(rule_type)spolicy rules: %(text_rules)s"

#: glance/api/policy.py:96
msgid "Unable to find policy file"
msgstr "Unable to find policy file"

#: glance/api/policy.py:106
#, python-format
msgid "Loading policy from %s"
msgstr "Loading policy from %s"

#: glance/api/policy.py:220 glance/quota/__init__.py:170
#: glance/store/__init__.py:586
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/middleware/cache.py:59
msgid "Initialized image cache middleware"
msgstr "Initialized image cache middleware"

#: glance/api/middleware/cache.py:127
#, python-format
msgid "Cache hit for image '%s'"
msgstr "Cache hit for image '%s'"

#: glance/api/middleware/cache.py:134
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"

#: glance/api/middleware/cache.py:225
#, python-format
msgid "could not find %s"
msgstr "could not find %s"

#: glance/api/middleware/cache.py:233
#, python-format
msgid "Removing image %s from cache"
msgstr "Removing image %s from cache"

#: glance/api/middleware/cache.py:245
msgid "Checksum header is missing."
msgstr "Checksum header is missing."

#: glance/api/middleware/cache_manage.py:74
msgid "Initialized image cache management middleware"
msgstr "Initialized image cache management middleware"

#: glance/api/middleware/context.py:31
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."

#: glance/api/middleware/context.py:36
msgid "Role used to identify an authenticated user as administrator."
msgstr "Role used to identify an authenticated user as administrator."

#: glance/api/middleware/context.py:39
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."

#: glance/api/middleware/context.py:55
msgid "Unable to retrieve request id from context"
msgstr "Unable to retrieve request id from context"

#: glance/api/middleware/context.py:112
msgid "Invalid service catalog json."
msgstr "Invalid service catalog json."

#: glance/api/middleware/gzip.py:35
msgid "Initialized gzip middleware"
msgstr ""

#: glance/api/middleware/version_negotiation.py:43
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr "Determining version of request: %(method)s %(path)s Accept: %(accept)s"

#: glance/api/middleware/version_negotiation.py:55
msgid "Using media-type versioning"
msgstr "Using media-type versioning"

#: glance/api/middleware/version_negotiation.py:59
msgid "Using url versioning"
msgstr "Using url versioning"

#: glance/api/middleware/version_negotiation.py:66
msgid "Unknown version. Returning version choices."
msgstr "Unknown version. Returning version choices."

#: glance/api/middleware/version_negotiation.py:71
#, python-format
msgid "Matched version: v%d"
msgstr "Matched version: v%d"

#: glance/api/v1/controller.py:43 glance/api/v1/members.py:74
#, python-format
msgid "Image with identifier %s not found"
msgstr "Image with identifier %s not found"

#: glance/api/v1/controller.py:48
msgid "Forbidden image access"
msgstr "Forbidden image access"

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is not active"
msgstr "Image %s is not active"

#: glance/api/v1/controller.py:83
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Store for image_id not found: %s"

#: glance/api/v1/images.py:81
#, python-format
msgid "Image name too long: %d"
msgstr "Image name too long: %d"

#: glance/api/v1/images.py:92
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."

#: glance/api/v1/images.py:164 glance/api/v1/images.py:208
#: glance/api/v1/images.py:242
#, python-format
msgid "Property '%s' is protected"
msgstr ""

#: glance/api/v1/images.py:386
#, python-format
msgid "External sourcing not supported for store %s"
msgstr "External sourcing not supported for store %s"

#: glance/api/v1/images.py:481
#, python-format
msgid "An image with identifier %s already exists"
msgstr "An image with identifier %s already exists"

#: glance/api/v1/images.py:488
#, python-format
msgid "Failed to reserve image. Got error: %(e)s"
msgstr "Failed to reserve image. Got error: %(e)s"

#: glance/api/v1/images.py:495
msgid "Forbidden to reserve image."
msgstr "Forbidden to reserve image."

#: glance/api/v1/images.py:522
#, python-format
msgid "Copy from external source failed: %s"
msgstr "Copy from external source failed: %s"

#: glance/api/v1/images.py:531
msgid "Content-Type must be application/octet-stream"
msgstr "Content-Type must be application/octet-stream"

#: glance/api/v1/images.py:542
#, python-format
msgid "Setting image %s to status 'saving'"
msgstr "Setting image %s to status 'saving'"

#: glance/api/v1/images.py:546
#, python-format
msgid "Uploading image data for image %(image_id)s to %(scheme)s store"
msgstr "Uploading image data for image %(image_id)s to %(scheme)s store"

#: glance/api/v1/images.py:584
#, python-format
msgid "Failed to activate image. Got error: %(e)s"
msgstr "Failed to activate image. Got error: %(e)s"

#: glance/api/v1/images.py:622
msgid "It's invalid to provide multiple image sources."
msgstr ""

#: glance/api/v1/images.py:633
msgid "Triggering asynchronous copy from external source"
msgstr "Triggering asynchronous copy from external source"

#: glance/api/v1/images.py:648
#, python-format
msgid ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)ps"
msgstr ""

#: glance/api/v1/images.py:762
msgid "Forbidden to update deleted image."
msgstr "Forbidden to update deleted image."

#: glance/api/v1/images.py:773
#, python-format
msgid "Forbidden to modify '%s' of active image."
msgstr ""

#: glance/api/v1/images.py:791
msgid "Cannot upload to an unqueued image"
msgstr "Cannot upload to an unqueued image"

#: glance/api/v1/images.py:808
msgid "Attempted to update Location field for an image not in queued status."
msgstr "Attempted to update Location field for an image not in queued status."

#: glance/api/v1/images.py:843 glance/registry/api/v1/images.py:440
#, python-format
msgid "Failed to update image metadata. Got error: %(e)s"
msgstr "Failed to update image metadata. Got error: %(e)s"

#: glance/api/v1/images.py:850
#, python-format
msgid "Failed to find image to update: %(e)s"
msgstr "Failed to find image to update: %(e)s"

#: glance/api/v1/images.py:857
#, python-format
msgid "Forbidden to update image: %(e)s"
msgstr "Forbidden to update image: %(e)s"

#: glance/api/v1/images.py:891
msgid "Image is protected"
msgstr "Image is protected"

#: glance/api/v1/images.py:898
#, python-format
msgid "Forbidden to delete a %s image."
msgstr ""

#: glance/api/v1/images.py:903
#, python-format
msgid "Image %s not found."
msgstr ""

#: glance/api/v1/images.py:929 glance/store/scrubber.py:179
#, python-format
msgid "Failed to find image to delete: %(e)s"
msgstr "Failed to find image to delete: %(e)s"

#: glance/api/v1/images.py:936
#, python-format
msgid "Forbidden to delete image: %(e)s"
msgstr "Forbidden to delete image: %(e)s"

#: glance/api/v1/images.py:959 glance/store/__init__.py:198
#, python-format
msgid "Store for scheme %s not found"
msgstr "Store for scheme %s not found"

#: glance/api/v1/images.py:975
#, python-format
msgid "Incoming image size of %s was not convertible to an integer."
msgstr "Incoming image size of %s was not convertible to an integer."

#: glance/api/v1/images.py:999 glance/api/v1/upload_utils.py:203
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Denying attempt to upload image larger than %d bytes."

#: glance/api/v1/members.py:39 glance/registry/api/v1/members.py:34
msgid "No authenticated user"
msgstr "No authenticated user"

#: glance/api/v1/members.py:51
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:78
msgid "Unauthorized image access"
msgstr "Unauthorized image access"

#: glance/api/v1/upload_utils.py:74
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:109
#, python-format
msgid "Cleaning up %s after exceeding the quota %s"
msgstr ""

#: glance/api/v1/upload_utils.py:118
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."

#: glance/api/v1/upload_utils.py:138
#, python-format
msgid ""
"Updating image %(image_id)s data. Checksum set to %(checksum)s, size set "
"to %(size)d"
msgstr ""
"Updating image %(image_id)s data. Checksum set to %(checksum)s, size set "
"to %(size)d"

#: glance/api/v1/upload_utils.py:151
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted"
" during the upload."
msgstr ""

#: glance/api/v1/upload_utils.py:167
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "Attempt to upload duplicate image: %s"

#: glance/api/v1/upload_utils.py:176
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "Forbidden upload attempt: %s"

#: glance/api/v1/upload_utils.py:185 glance/api/v2/image_data.py:92
#: glance/api/v2/image_data.py:98 glance/notifier/__init__.py:204
#, python-format
msgid "Image storage media is full: %s"
msgstr "Image storage media is full: %s"

#: glance/api/v1/upload_utils.py:194 glance/api/v2/image_data.py:116
#: glance/notifier/__init__.py:208
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Insufficient permissions on image storage media: %s"

#: glance/api/v1/upload_utils.py:213 glance/api/v2/images.py:127
#, python-format
msgid "Denying attempt to upload image because it exceeds the .quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:227
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v1/upload_utils.py:234
msgid "Client disconnected before sending all data to backend"
msgstr ""

#: glance/api/v1/upload_utils.py:242
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:58
#, python-format
msgid ""
"Image %s could not be found after upload.The image may have been deleted "
"during the upload: %s Cleaning up the chunks uploaded"
msgstr ""

#: glance/api/v2/image_data.py:77
#, python-format
msgid "Unable to upload duplicate image data for image: %s"
msgstr "Unable to upload duplicate image data for image: %s"

#: glance/api/v2/image_data.py:83
#, python-format
msgid "Not allowed to upload image data for image %s"
msgstr "Not allowed to upload image data for image %s"

#: glance/api/v2/image_data.py:104
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:110
msgid "The incoming image is too large: %"
msgstr ""

#: glance/api/v2/image_data.py:122
msgid "Failed to upload image data due to HTTP error"
msgstr "Failed to upload image data due to HTTP error"

#: glance/api/v2/image_data.py:126
msgid "Failed to upload image data due to internal error"
msgstr "Failed to upload image data due to internal error"

#: glance/api/v2/image_data.py:135 glance/store/__init__.py:652
msgid "No image data could be found"
msgstr "No image data could be found"

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:278
msgid "Body expected in request."
msgstr "Body expected in request."

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr "Member to be added not specified"

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr "Status not specified"

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr "An identifier for the image member (tenantId)"

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:631
msgid "An identifier for the image"
msgstr "An identifier for the image"

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr "Date and time of image member creation"

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr "Date and time of last modification of image member"

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr "The status of this image member"

#: glance/api/v2/images.py:120
#, python-format
msgid "Failed to find image %(image_id)s to update"
msgstr "Failed to find image %(image_id)s to update"

#: glance/api/v2/images.py:147 glance/api/v2/images.py:175
#, python-format
msgid "Property %s does not exist."
msgstr "Property %s does not exist."

#: glance/api/v2/images.py:159
#, python-format
msgid "Property %s already present."
msgstr "Property %s already present."

#: glance/api/v2/images.py:170
#, python-format
msgid "Property %s may not be removed."
msgstr "Property %s may not be removed."

#: glance/api/v2/images.py:208
msgid "Cannot replace locations from a non-empty list to a non-empty list."
msgstr ""

#: glance/api/v2/images.py:231
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:246
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:310 glance/api/v2/images.py:332
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "Unable to find '%s' in JSON Schema change"

#: glance/api/v2/images.py:318
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."

#: glance/api/v2/images.py:323
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."

#: glance/api/v2/images.py:360
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Pointer `%s` does not start with \"/\"."

#: glance/api/v2/images.py:363
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:366
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:369
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr "Pointer `%s` contains \"~\" not part of a recognized escape sequence."

#: glance/api/v2/images.py:378
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Operation \"%s\" requires a member named \"value\"."

#: glance/api/v2/images.py:418
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:430
msgid "Unrecognized JSON Schema draft version"
msgstr "Unrecognized JSON Schema draft version"

#: glance/api/v2/images.py:451
msgid "Request body must be a JSON array of operation objects."
msgstr "Request body must be a JSON array of operation objects."

#: glance/api/v2/images.py:456
msgid "Operations must be JSON objects."
msgstr "Operations must be JSON objects."

#: glance/api/v2/images.py:478 glance/registry/api/v1/images.py:240
msgid "limit param must be an integer"
msgstr "limit param must be an integer"

#: glance/api/v2/images.py:482 glance/registry/api/v1/images.py:243
msgid "limit param must be positive"
msgstr "limit param must be positive"

#: glance/api/v2/images.py:489
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Invalid sort direction: %s"

#: glance/api/v2/images.py:496
#, python-format
msgid "Invalid status: %s"
msgstr "Invalid status: %s"

#: glance/api/v2/images.py:505
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Invalid visibility value: %s"

#: glance/api/v2/images.py:637
msgid "Descriptive name for the image"
msgstr "Descriptive name for the image"

#: glance/api/v2/images.py:642
msgid "Status of the image (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:648
msgid "Scope of image accessibility"
msgstr "Scope of image accessibility"

#: glance/api/v2/images.py:653
msgid "If true, image will not be deletable."
msgstr "If true, image will not be deletable."

#: glance/api/v2/images.py:657
msgid "md5 hash of image contents. (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:663
msgid "Size of image file in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:667
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:673
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:679
msgid "Date and time of image registration (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:687
msgid "Date and time of the last image modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:693
msgid "List of strings related to the image"
msgstr "List of strings related to the image"

#: glance/api/v2/images.py:701
msgid "URL to access the image file kept in external store (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:706
msgid "Amount of ram (in MB) required to boot image."
msgstr "Amount of ram (in MB) required to boot image."

#: glance/api/v2/images.py:710
msgid "Amount of disk space (in GB) required to boot image."
msgstr "Amount of disk space (in GB) required to boot image."

#: glance/api/v2/images.py:740
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/images.py:779
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""
"Could not find schema properties file %s. Continuing without custom "
"properties"

#: glance/cmd/replicator.py:54
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did "
"not find it. This indicates that we do not have permissions to see all "
"the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:104
#, python-format
msgid ""
"Request: %(method)s http://%(server)s:%(port)s%(url)s with headers "
"%(headers)s"
msgstr ""

#: glance/cmd/replicator.py:117
#, python-format
msgid "Response: %(code)s %(status)s %(headers)s"
msgstr ""

#: glance/cmd/replicator.py:239 glance/cmd/replicator.py:258
msgid "Image post done"
msgstr ""

#: glance/cmd/replicator.py:281 glance/cmd/replicator.py:316
#: glance/cmd/replicator.py:401 glance/cmd/replicator.py:480
#: glance/cmd/replicator.py:557
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:286 glance/cmd/replicator.py:322
#: glance/cmd/replicator.py:407 glance/cmd/replicator.py:487
#: glance/cmd/replicator.py:564
msgid "Bad format of the given arguments."
msgstr ""

#: glance/cmd/replicator.py:297
#, python-format
msgid "Considering image: %(image)s"
msgstr ""

#: glance/cmd/replicator.py:302
#, python-format
msgid "Total size is %d bytes across %d images"
msgstr ""

#: glance/cmd/replicator.py:330 glance/cmd/replicator.py:420
#, python-format
msgid "Considering: %s"
msgstr ""

#: glance/cmd/replicator.py:334
msgid "... storing"
msgstr ""

#: glance/cmd/replicator.py:345
msgid "... image is active"
msgstr ""

#: glance/cmd/replicator.py:365
#, python-format
msgid "metadata diff -- master has extra keys: %(keys)s"
msgstr ""

#: glance/cmd/replicator.py:371
#, python-format
msgid ""
"metadata diff -- value differs for key %(key)s: master "
"\"%(master_value)s\" vs slave \"%(slave_value)s\""
msgstr ""

#: glance/cmd/replicator.py:429
#, python-format
msgid "Stripping %(header)s from saved metadata"
msgstr ""

#: glance/cmd/replicator.py:437
#, python-format
msgid "Image %s already present"
msgstr ""

#: glance/cmd/replicator.py:441 glance/cmd/replicator.py:521
#: glance/cmd/replicator.py:587
#, python-format
msgid "Stripping %(header)s from slave metadata"
msgstr ""

#: glance/cmd/replicator.py:446 glance/cmd/replicator.py:526
msgid "... metadata has changed"
msgstr ""

#: glance/cmd/replicator.py:453
msgid "... dump is missing image data, skipping"
msgstr ""

#: glance/cmd/replicator.py:502
#, python-format
msgid "Considering %(id)s"
msgstr ""

#: glance/cmd/replicator.py:505 glance/cmd/replicator.py:517
#: glance/cmd/replicator.py:583
#, python-format
msgid "Stripping %(header)s from master metadata"
msgstr ""

#: glance/cmd/replicator.py:532
#, python-format
msgid "%s is being synced"
msgstr ""

#: glance/cmd/replicator.py:593
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, "
"destination is %(slave_value)s)"
msgstr ""

#: glance/cmd/replicator.py:603
#, python-format
msgid "%(image_id)s is identical"
msgstr ""

#: glance/cmd/replicator.py:607
#, python-format
msgid "%s: entirely missing from the destination"
msgstr ""

#: glance/cmd/replicator.py:714
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:188 glance/common/auth.py:228
#, python-format
msgid "Unexpected response: %s"
msgstr "Unexpected response: %s"

#: glance/common/auth.py:256
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Unknown auth strategy '%s'"

#: glance/common/auth.py:277
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr "Encountered service with no \"type\": %s"

#: glance/common/client.py:238
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"

#: glance/common/client.py:246
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"

#: glance/common/client.py:255
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "The key file you specified %s does not exist"

#: glance/common/client.py:262
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "The cert file you specified %s does not exist"

#: glance/common/client.py:269
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "The CA file you specified %s does not exist"

#: glance/common/client.py:307
#, python-format
msgid "Configuring from URL: %s"
msgstr "Configuring from URL: %s"

#: glance/common/client.py:319
#, python-format
msgid "Appending doc_root %(doc_root)s to URL %(url)s"
msgstr "Appending doc_root %(doc_root)s to URL %(url)s"

#: glance/common/client.py:408
#, python-format
msgid "Constructed URL: %s"
msgstr "Constructed URL: %s"

#: glance/common/config.py:36
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""

#: glance/common/config.py:42
msgid "Name of the paste configuration file."
msgstr "Name of the paste configuration file."

#: glance/common/config.py:46
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"

#: glance/common/config.py:49
msgid "Python module path of data access API"
msgstr "Python module path of data access API"

#: glance/common/config.py:51
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"

#: glance/common/config.py:54
msgid "Maximum permissible number of items that could be returned by a request"
msgstr "Maximum permissible number of items that could be returned by a request"

#: glance/common/config.py:57
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can bea security risk, so use this"
" setting with caution!"
msgstr ""

#: glance/common/config.py:61
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance/common/config.py:66
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."

#: glance/common/config.py:69
msgid ""
"Set a system wide quota for every user.  This value is the total number "
"of bytes that a user can use across all storage systems.  A value of 0 "
"means unlimited."
msgstr ""

#: glance/common/config.py:73
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:75
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:77
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "The hostname/IP of the pydev process listening for debug connections"

#: glance/common/config.py:80
msgid "The port on which a pydev process is listening for connections."
msgstr "The port on which a pydev process is listening for connections."

#: glance/common/config.py:83
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."

#: glance/common/config.py:167
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr "Loading %(app_name)s from %(conf_file)s"

#: glance/common/config.py:178
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"

#: glance/common/exception.py:39
msgid "An unknown exception occurred"
msgstr "An unknown exception occurred"

#: glance/common/exception.py:57
msgid "Missing required argument."
msgstr "Missing required argument."

#: glance/common/exception.py:61
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Missing required credential: %(required)s"

#: glance/common/exception.py:65
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""

#: glance/common/exception.py:70
msgid "An object with the specified identifier was not found."
msgstr "An object with the specified identifier was not found."

#: glance/common/exception.py:74
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr "Unknown scheme '%(scheme)s' found in URI"

#: glance/common/exception.py:78
msgid "The Store URI was malformed."
msgstr "The Store URI was malformed."

#: glance/common/exception.py:82
msgid "An object with the same identifier already exists."
msgstr "An object with the same identifier already exists."

#: glance/common/exception.py:86
msgid "There is not enough disk space on the image storage media."
msgstr "There is not enough disk space on the image storage media."

#: glance/common/exception.py:90
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""

#: glance/common/exception.py:95
msgid "Permission to write image storage media denied."
msgstr "Permission to write image storage media denied."

#: glance/common/exception.py:99
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "Connect error/bad request to Auth service at URL %(url)s."

#: glance/common/exception.py:103
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Auth service at URL %(url)s not found."

#: glance/common/exception.py:107
msgid "Authorization failed."
msgstr "Authorization failed."

#: glance/common/exception.py:111
msgid "You are not authenticated."
msgstr "You are not authenticated."

#: glance/common/exception.py:115 glance/common/exception.py:119
#: glance/common/exception.py:128
msgid "You are not authorized to complete this action."
msgstr "You are not authorized to complete this action."

#: glance/common/exception.py:123
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Image %(image_id)s is protected and cannot be deleted."

#: glance/common/exception.py:132
msgid "Data supplied was not valid."
msgstr "Data supplied was not valid."

#: glance/common/exception.py:136
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr "Sort key supplied was not valid."

#: glance/common/exception.py:140
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:144
msgid "Unable to filter using the specified range."
msgstr "Unable to filter using the specified range."

#: glance/common/exception.py:148
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Attribute '%(property)s' is read-only."

#: glance/common/exception.py:152
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Attribute '%(property)s' is reserved."

#: glance/common/exception.py:156
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Redirecting to %(uri)s for authorization."

#: glance/common/exception.py:160
msgid "There was an error migrating the database."
msgstr "There was an error migrating the database."

#: glance/common/exception.py:164
msgid "There was an error connecting to a server"
msgstr "There was an error connecting to a server"

#: glance/common/exception.py:168
msgid "There was an error configuring the client."
msgstr "There was an error configuring the client."

#: glance/common/exception.py:172
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"

#: glance/common/exception.py:178
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:189
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."

#: glance/common/exception.py:200
msgid "The request returned 500 Internal Server Error."
msgstr "The request returned 500 Internal Server Error."

#: glance/common/exception.py:204
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"

#: glance/common/exception.py:209
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Invalid content type %(content_type)s"

#: glance/common/exception.py:213
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "Registry was not configured correctly on API server. Reason: %(reason)s"

#: glance/common/exception.py:218
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"

#: glance/common/exception.py:223
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"

#: glance/common/exception.py:228
msgid "Deleting images from this store is not supported."
msgstr "Deleting images from this store is not supported."

#: glance/common/exception.py:232
msgid "Getting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:236
msgid "Adding images to this store is not supported."
msgstr ""

#: glance/common/exception.py:240
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr "Configuration for store failed. Adding images to this store is disabled."

#: glance/common/exception.py:245
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr "'%(strategy)s' is not an available notifier strategy."

#: glance/common/exception.py:249
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "Maximum redirects (%(redirects)s) was exceeded."

#: glance/common/exception.py:253
msgid "Received invalid HTTP redirect."
msgstr "Received invalid HTTP redirect."

#: glance/common/exception.py:257
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Response from Keystone does not contain a Glance endpoint."

#: glance/common/exception.py:261
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."

#: glance/common/exception.py:267
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Server worker creation failed: %(reason)s."

#: glance/common/exception.py:271
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Unable to load schema: %(reason)s"

#: glance/common/exception.py:275
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "Provided object does not match schema '%(schema)s': %(reason)s"

#: glance/common/exception.py:280
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr "Provided header feature is unsupported: %(feature)s"

#: glance/common/exception.py:284
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."

#: glance/common/exception.py:289
msgid "The provided image is too large."
msgstr "The provided image is too large."

#: glance/common/exception.py:293
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:297
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/property_utils.py:40
msgid "The location of the property protection file."
msgstr ""

#: glance/common/property_utils.py:43
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in"
" the property protection file."
msgstr ""

#: glance/common/property_utils.py:73
#, python-format
msgid "Couldn't find property protection file %s:%s."
msgstr ""

#: glance/common/property_utils.py:79
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:96
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be"
" combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:125
#, python-format
msgid "Encountered a malformed property protection rule %s:%s."
msgstr ""

#: glance/common/property_utils.py:168
#, python-format
msgid ""
"Malformed property protection rule '%s': '@' and '!' are mutually "
"exclusive"
msgstr ""

#: glance/common/rpc.py:140
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:145
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:152
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:161
msgid "Command not found"
msgstr ""

#: glance/common/rpc.py:183
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/utils.py:105
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr "Error: cooperative_iter exception %s"

#: glance/common/utils.py:253
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:418
msgid "Read-only access"
msgstr "Read-only access"

#: glance/common/utils.py:464
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: glance/common/utils.py:495
#, python-format
msgid "There is a problem with your %s %s.  Please verify it.  Error: %s"
msgstr ""

#: glance/common/utils.py:499
#, python-format
msgid "There is a problem with your %s %s.  Please verify it. OpenSSL error: %s"
msgstr ""

#: glance/common/utils.py:510
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert %s and "
"key %s belong together.  OpenSSL error %s"
msgstr ""

#: glance/common/wsgi.py:51
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."

#: glance/common/wsgi.py:54
msgid "The port on which the server will listen."
msgstr "The port on which the server will listen."

#: glance/common/wsgi.py:59
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr "The backlog value that will be used when creating the TCP listener socket."

#: glance/common/wsgi.py:62
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in "
"seconds that the connection must be idle before TCP starts sending "
"keepalive probes."
msgstr ""

#: glance/common/wsgi.py:65
msgid "CA certificate file to use to verify connecting clients."
msgstr "CA certificate file to use to verify connecting clients."

#: glance/common/wsgi.py:67
msgid "Certificate file to use when starting API server securely."
msgstr "Certificate file to use when starting API server securely."

#: glance/common/wsgi.py:69
msgid "Private key file to use when starting API server securely."
msgstr "Private key file to use when starting API server securely."

#: glance/common/wsgi.py:75
msgid ""
"The number of child process workers that will be created to service API "
"requests."
msgstr ""
"The number of child process workers that will be created to service API "
"requests."

#: glance/common/wsgi.py:78
msgid ""
"Name of eventlet hub to use. Traditionally, we have only supported "
"'poll', however 'selects' may be appropriate for some platforms. See "
"http://eventlet.net/doc/hubs.html for more details."
msgstr ""

#: glance/common/wsgi.py:135
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"

#: glance/common/wsgi.py:173
#, python-format
msgid "Could not bind to %s:%s after trying for 30 seconds"
msgstr "Could not bind to %s:%s after trying for 30 seconds"

#: glance/common/wsgi.py:245 glance/openstack/common/service.py:240
#, python-format
msgid "Starting %d workers"
msgstr "Starting %d workers"

#: glance/common/wsgi.py:260
#, python-format
msgid "Removing dead child %s"
msgstr "Removing dead child %s"

#: glance/common/wsgi.py:263
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "Not respawning child %d, cannot recover from termination"

#: glance/common/wsgi.py:267
msgid "All workers have terminated. Exiting"
msgstr "All workers have terminated. Exiting"

#: glance/common/wsgi.py:275
msgid "Caught keyboard interrupt. Exiting."
msgstr "Caught keyboard interrupt. Exiting."

#: glance/common/wsgi.py:279
msgid "Exited"
msgstr "Exited"

#: glance/common/wsgi.py:301
#, python-format
msgid "Child %d exiting normally"
msgstr "Child %d exiting normally"

#: glance/common/wsgi.py:306
#, python-format
msgid "Started child %s"
msgstr "Started child %s"

#: glance/common/wsgi.py:319
#, python-format
msgid "eventlet '%s' hub is not available on this platform"
msgstr ""

#: glance/common/wsgi.py:336
msgid "Starting single process server"
msgstr "Starting single process server"

#: glance/common/wsgi.py:541
msgid "Malformed JSON in request body."
msgstr "Malformed JSON in request body."

#: glance/db/__init__.py:73 glance/db/__init__.py:174 glance/db/__init__.py:186
#: glance/db/sqlalchemy/api.py:329
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:247
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""

#: glance/db/__init__.py:263
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/simple/api.py:40
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"

#: glance/db/simple/api.py:45
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr "Returning %(funcname)s: %(output)s"

#: glance/db/simple/api.py:235 glance/db/sqlalchemy/api.py:584
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Unable to filter on a range with a non-numeric value."

#: glance/db/simple/api.py:307
#, python-format
msgid "Could not find image %s"
msgstr "Could not find image %s"

#: glance/db/simple/api.py:311
msgid "Unable to get deleted image"
msgstr "Unable to get deleted image"

#: glance/db/simple/api.py:315
msgid "Unable to get unowned image"
msgstr "Unable to get unowned image"

#: glance/db/simple/api.py:720 glance/db/simple/api.py:766
#: glance/db/sqlalchemy/api.py:1192 glance/db/sqlalchemy/api.py:1281
#, python-format
msgid "No task found with ID %s"
msgstr ""

#: glance/db/simple/api.py:740
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:745
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:750 glance/db/sqlalchemy/api.py:1287
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr ""

#: glance/db/simple/api.py:862
msgid "Task does not exist"
msgstr ""

#: glance/db/sqlalchemy/api.py:56
#, python-format
msgid ""
"A valid SQLAlchemy connection string for the registry database. Default: "
"%(default)s"
msgstr ""

#: glance/db/sqlalchemy/api.py:62
msgid ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."
msgstr ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."

#: glance/db/sqlalchemy/api.py:65
msgid "The number of times to retry a connection to the SQLserver."
msgstr "The number of times to retry a connection to the SQLserver."

#: glance/db/sqlalchemy/api.py:68
msgid ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."
msgstr ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."

#: glance/db/sqlalchemy/api.py:71
msgid "A boolean that determines if the database will be automatically created."
msgstr "A boolean that determines if the database will be automatically created."

#: glance/db/sqlalchemy/api.py:74
msgid "Enable debug logging in sqlalchemy which prints every query and result"
msgstr ""

#: glance/db/sqlalchemy/api.py:137
msgid "Attempted to modify image user did not own."
msgstr "Attempted to modify image user did not own."

#: glance/db/sqlalchemy/api.py:138
msgid "You do not own this image"
msgstr "You do not own this image"

#: glance/db/sqlalchemy/api.py:184
#, python-format
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"
msgstr ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"

#: glance/db/sqlalchemy/api.py:194
msgid "auto-creating glance registry DB"
msgstr "auto-creating glance registry DB"

#: glance/db/sqlalchemy/api.py:202
msgid "not auto-creating glance registry DB"
msgstr "not auto-creating glance registry DB"

#: glance/db/sqlalchemy/api.py:241
#, python-format
msgid "SQL connection failed. %d attempts left."
msgstr "SQL connection failed. %d attempts left."

#: glance/db/sqlalchemy/api.py:335
#, python-format
msgid "Forbidding request, image %s not visible"
msgstr ""

#: glance/db/sqlalchemy/api.py:456
#: glance/openstack/common/db/sqlalchemy/utils.py:99
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id not in sort_keys; is sort_keys unique?"

#: glance/db/sqlalchemy/api.py:514
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Unknown sort direction, must be 'desc' or 'asc'"

#: glance/db/sqlalchemy/migration.py:44
msgid "database is not under migration control"
msgstr "database is not under migration control"

#: glance/db/sqlalchemy/migration.py:59
#, python-format
msgid "Upgrading database to version %s"
msgstr "Upgrading database to version %s"

#: glance/db/sqlalchemy/migration.py:74
#, python-format
msgid "Downgrading database to version %s"
msgstr "Downgrading database to version %s"

#: glance/db/sqlalchemy/migration.py:87
msgid "database is already under migration control"
msgstr "database is already under migration control"

#: glance/db/sqlalchemy/migrate_repo/schema.py:98
#, python-format
msgid "creating table %(table)s"
msgstr "creating table %(table)s"

#: glance/db/sqlalchemy/migrate_repo/schema.py:104
#, python-format
msgid "dropping table %(table)s"
msgstr "dropping table %(table)s"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:84
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:147
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:91
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:154
#, python-format
msgid "Invalid store uri for image %s: %s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:122
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:185
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Badly formed credentials '%(creds)s' in Swift URI"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:135
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:198
#: glance/store/swift.py:210
msgid "Badly formed credentials in Swift URI."
msgstr "Badly formed credentials in Swift URI."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:153
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:216
#: glance/store/s3.py:167
#, python-format
msgid "Badly formed S3 URI: %s"
msgstr "Badly formed S3 URI: %s"

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:68
msgid ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."
msgstr ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:89
#, python-format
msgid "Failed to decrypt location value for image %s"
msgstr "Failed to decrypt location value for image %s"

#: glance/domain/__init__.py:27
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/domain/__init__.py:32
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/domain/__init__.py:124
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Property %s must be set prior to saving data."

#: glance/domain/__init__.py:126
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Properties %s must be set prior to saving data."

#: glance/domain/__init__.py:205
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Status must be \"pending\", \"accepted\" or \"rejected\"."

#: glance/image_cache/__init__.py:36
msgid "The driver to use for image cache management."
msgstr "The driver to use for image cache management."

#: glance/image_cache/__init__.py:38
msgid "The maximum size in bytes that the cache can use."
msgstr "The maximum size in bytes that the cache can use."

#: glance/image_cache/__init__.py:40
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed"
msgstr ""
"The amount of time to let an image remain in the cache without being "
"accessed"

#: glance/image_cache/__init__.py:43
msgid "Base directory that the Image Cache uses."
msgstr "Base directory that the Image Cache uses."

#: glance/image_cache/__init__.py:65
#, python-format
msgid "Image cache loaded driver '%s'."
msgstr "Image cache loaded driver '%s'."

#: glance/image_cache/__init__.py:68
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."

#: glance/image_cache/__init__.py:75 glance/image_cache/__init__.py:94
msgid "Defaulting to SQLite driver."
msgstr "Defaulting to SQLite driver."

#: glance/image_cache/__init__.py:89
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"

#: glance/image_cache/__init__.py:176
msgid "Image cache has free space, skipping prune..."
msgstr "Image cache has free space, skipping prune..."

#: glance/image_cache/__init__.py:180
#, python-format
msgid ""
"Image cache currently %(overage)d bytes over max size. Starting prune to "
"max size of %(max_size)d "
msgstr ""
"Image cache currently %(overage)d bytes over max size. Starting prune to "
"max size of %(max_size)d "

#: glance/image_cache/__init__.py:189
#, python-format
msgid "Pruning '%(image_id)s' to free %(size)d bytes"
msgstr "Pruning '%(image_id)s' to free %(size)d bytes"

#: glance/image_cache/__init__.py:197
#, python-format
msgid ""
"Pruning finished pruning. Pruned %(total_files_pruned)d and "
"%(total_bytes_pruned)d."
msgstr ""
"Pruning finished pruning. Pruned %(total_files_pruned)d and "
"%(total_bytes_pruned)d."

#: glance/image_cache/__init__.py:236
#, python-format
msgid "Tee'ing image '%s' into cache"
msgstr "Tee'ing image '%s' into cache"

#: glance/image_cache/__init__.py:255
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr "Checksum verification failed. Aborted caching of image '%s'."

#: glance/image_cache/__init__.py:265
#, python-format
msgid ""
"Exception encountered while tee'ing image '%s' into cache: %s. Continuing"
" with response."
msgstr ""
"Exception encountered while tee'ing image '%s' into cache: %s. Continuing"
" with response."

#: glance/image_cache/prefetcher.py:48
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr "Image '%s' is not active. Not caching."

#: glance/image_cache/prefetcher.py:53
#, python-format
msgid "No metadata found for image '%s'"
msgstr "No metadata found for image '%s'"

#: glance/image_cache/prefetcher.py:58
#, python-format
msgid "Caching image '%s'"
msgstr "Caching image '%s'"

#: glance/image_cache/prefetcher.py:70
msgid "Nothing to prefetch."
msgstr "Nothing to prefetch."

#: glance/image_cache/prefetcher.py:74
#, python-format
msgid "Found %d images to prefetch"
msgstr "Found %d images to prefetch"

#: glance/image_cache/prefetcher.py:80
msgid "Failed to successfully cache all images in queue."
msgstr "Failed to successfully cache all images in queue."

#: glance/image_cache/prefetcher.py:84
#, python-format
msgid "Successfully cached all %d images"
msgstr "Successfully cached all %d images"

#: glance/image_cache/drivers/base.py:56
#, python-format
msgid "Failed to read %s from config"
msgstr "Failed to read %s from config"

#: glance/image_cache/drivers/sqlite.py:40
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"The path to the sqlite file database that will be used for image cache "
"management."

#: glance/image_cache/drivers/sqlite.py:122
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr "Failed to initialize the image cache database. Got error: %s"

#: glance/image_cache/drivers/sqlite.py:161
#: glance/image_cache/drivers/xattr.py:146
msgid "Gathering cached image entries."
msgstr "Gathering cached image entries."

#: glance/image_cache/drivers/sqlite.py:300
#: glance/image_cache/drivers/xattr.py:274
#, python-format
msgid "Fetch finished, moving '%(incomplete_path)s' to '%(final_path)s'"
msgstr "Fetch finished, moving '%(incomplete_path)s' to '%(final_path)s'"

#: glance/image_cache/drivers/sqlite.py:324
#: glance/image_cache/drivers/xattr.py:290
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"

#: glance/image_cache/drivers/sqlite.py:389
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr "Error executing SQLite call. Got error: %s"

#: glance/image_cache/drivers/sqlite.py:405
#: glance/image_cache/drivers/xattr.py:338
#, python-format
msgid "Not queueing image '%s'. Already cached."
msgstr "Not queueing image '%s'. Already cached."

#: glance/image_cache/drivers/sqlite.py:410
#: glance/image_cache/drivers/xattr.py:343
#, python-format
msgid "Not queueing image '%s'. Already being written to cache"
msgstr "Not queueing image '%s'. Already being written to cache"

#: glance/image_cache/drivers/sqlite.py:416
#: glance/image_cache/drivers/xattr.py:349
#, python-format
msgid "Not queueing image '%s'. Already queued."
msgstr "Not queueing image '%s'. Already queued."

#: glance/image_cache/drivers/sqlite.py:434
#, python-format
msgid "Removed invalid cache file %s"
msgstr "Removed invalid cache file %s"

#: glance/image_cache/drivers/sqlite.py:448
#, python-format
msgid "Removed stalled cache file %s"
msgstr "Removed stalled cache file %s"

#: glance/image_cache/drivers/sqlite.py:450
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:484
#: glance/image_cache/drivers/xattr.py:439
#, python-format
msgid "Deleting image cache file '%s'"
msgstr "Deleting image cache file '%s'"

#: glance/image_cache/drivers/sqlite.py:487
#: glance/image_cache/drivers/xattr.py:442
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr "Cached image file '%s' doesn't exist, unable to delete"

#: glance/image_cache/drivers/xattr.py:106
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."

#: glance/image_cache/drivers/xattr.py:282
#, python-format
msgid "Removing image '%s' from queue after caching it."
msgstr "Removing image '%s' from queue after caching it."

#: glance/image_cache/drivers/xattr.py:354
#, python-format
msgid "Queueing image '%s'."
msgstr "Queueing image '%s'."

#: glance/image_cache/drivers/xattr.py:384
#, python-format
msgid "No grace period, reaping '%(path)s' immediately"
msgstr "No grace period, reaping '%(path)s' immediately"

#: glance/image_cache/drivers/xattr.py:389
#, python-format
msgid "Cache entry '%(path)s' exceeds grace period, (%(age)i s > %(grace)i s)"
msgstr "Cache entry '%(path)s' exceeds grace period, (%(age)i s > %(grace)i s)"

#: glance/image_cache/drivers/xattr.py:395
#, python-format
msgid "Reaped %(reaped)s %(entry_type)s cache entries"
msgstr "Reaped %(reaped)s %(entry_type)s cache entries"

#: glance/notifier/__init__.py:34
msgid ""
"Notifications can be sent when images are create, updated or deleted. "
"There are three methods of sending notifications, logging (via the "
"log_file directive), rabbit (via a rabbitmq queue), qpid (via a Qpid "
"message queue), or noop (no notifications sent, the default)."
msgstr ""
"Notifications can be sent when images are create, updated or deleted. "
"There are three methods of sending notifications, logging (via the "
"log_file directive), rabbit (via a rabbitmq queue), qpid (via a Qpid "
"message queue), or noop (no notifications sent, the default)."

#: glance/notifier/__init__.py:63
#, python-format
msgid "Converted strategy alias %s to %s"
msgstr "Converted strategy alias %s to %s"

#: glance/notifier/__init__.py:67
#, python-format
msgid "No strategy alias found for %s"
msgstr "No strategy alias found for %s"

#: glance/notifier/__init__.py:213
#, python-format
msgid "Cannot save data for image %s: %s"
msgstr ""

#: glance/notifier/__init__.py:218
#, python-format
msgid "Unable to upload duplicate image data for image %s: %s"
msgstr ""

#: glance/notifier/__init__.py:223
#, python-format
msgid "Not allowed to upload image data for image %s: %s"
msgstr ""

#: glance/notifier/__init__.py:228
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted"
" during the upload: %s"
msgstr ""

#: glance/notifier/__init__.py:234
#, python-format
msgid "Failed to upload image data for image %s due to HTTP error: %s"
msgstr ""

#: glance/notifier/__init__.py:240
#, python-format
msgid "Failed to upload image data for image %s due to internal error: %s"
msgstr ""

#: glance/notifier/notify_kombu.py:31
msgid "The host name of the rabbitmq server"
msgstr "The host name of the rabbitmq server"

#: glance/notifier/notify_kombu.py:33
msgid "The port on which the rabbitmq server is listening"
msgstr "The port on which the rabbitmq server is listening"

#: glance/notifier/notify_kombu.py:35
msgid "A boolean value indicating if the selected rabbitmq server uses SSL."
msgstr "A boolean value indicating if the selected rabbitmq server uses SSL."

#: glance/notifier/notify_kombu.py:38
msgid "The user ID for authentication with rabbitmq."
msgstr "The user ID for authentication with rabbitmq."

#: glance/notifier/notify_kombu.py:40
msgid ""
"The password that will be used for authentication with the rabbitmq "
"server."
msgstr ""
"The password that will be used for authentication with the rabbitmq "
"server."

#: glance/notifier/notify_kombu.py:43
msgid "The virtual host used in the rabbitmq connection."
msgstr "The virtual host used in the rabbitmq connection."

#: glance/notifier/notify_kombu.py:45
msgid "Exchange name to use for connection when using rabbit strategy."
msgstr "Exchange name to use for connection when using rabbit strategy."

#: glance/notifier/notify_kombu.py:48
msgid "Topic to use for connection when using rabbit strategy."
msgstr "Topic to use for connection when using rabbit strategy."

#: glance/notifier/notify_kombu.py:51
msgid "The maximum number of times to attempt to connect to the AMQP server."
msgstr "The maximum number of times to attempt to connect to the AMQP server."

#: glance/notifier/notify_kombu.py:54
msgid ""
"This value multiplied by the number of connection attempts gives the "
"amount of time in seconds to sleep between connection attempts to the "
"AMQP server."
msgstr ""
"This value multiplied by the number of connection attempts gives the "
"amount of time in seconds to sleep between connection attempts to the "
"AMQP server."

#: glance/notifier/notify_kombu.py:58
msgid ""
"The maximum amount of time to wait between connection attempts.  The "
"delay time will be the smaller of this value and the value of "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far>."
msgstr ""
"The maximum amount of time to wait between connection attempts.  The "
"delay time will be the smaller of this value and the value of "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far>."

#: glance/notifier/notify_kombu.py:110
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr "Reconnecting to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:114
#, python-format
msgid "Connecting to AMQP server on %(hostname)s:%(port)d"
msgstr "Connecting to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:144
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr "Connected to AMQP server on %(hostname)s:%(port)d"

#: glance/notifier/notify_kombu.py:173
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"

#: glance/notifier/notify_kombu.py:185
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."

#: glance/notifier/notify_kombu.py:192
#, python-format
msgid "Notification with priority %(priority)s failed: msg=%(msg)s"
msgstr "Notification with priority %(priority)s failed: msg=%(msg)s"

#: glance/notifier/notify_kombu.py:231
#, python-format
msgid "Unable to send notification: %s"
msgstr "Unable to send notification: %s"

#: glance/notifier/notify_qpid.py:110
#, python-format
msgid "Connected to AMQP server on %s"
msgstr "Connected to AMQP server on %s"

#: glance/notifier/notify_qpid.py:139
#, python-format
msgid "Notification error.  Priority: %(priority)s Message: %(msg)s"
msgstr ""

#: glance/openstack/common/excutils.py:48
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: glance/openstack/common/fileutils.py:64
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: glance/openstack/common/lockutils.py:105
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: glance/openstack/common/lockutils.py:170
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:179
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:189
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: glance/openstack/common/lockutils.py:207
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: glance/openstack/common/lockutils.py:211
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: glance/openstack/common/lockutils.py:249
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:253
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: glance/openstack/common/log.py:250
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecated: %s"

#: glance/openstack/common/log.py:349
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: glance/openstack/common/log.py:400
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: glance/openstack/common/log.py:570
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config: %(msg)s"

#: glance/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: glance/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: glance/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: glance/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: glance/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr "Failed to understand rule %(rule)s"

#: glance/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: glance/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr "Failed to understand rule %(rule)r"

#: glance/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: glance/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: glance/openstack/common/processutils.py:167
#: glance/openstack/common/processutils.py:240
#, python-format
msgid "Result was %s"
msgstr ""

#: glance/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: glance/openstack/common/processutils.py:219
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: glance/openstack/common/processutils.py:221
msgid "Environment not supported over SSH"
msgstr ""

#: glance/openstack/common/processutils.py:225
msgid "process_input not supported over SSH"
msgstr ""

#: glance/openstack/common/service.py:112
#: glance/openstack/common/service.py:275
msgid "Full set of CONF:"
msgstr ""

#: glance/openstack/common/service.py:121
#: glance/openstack/common/service.py:218
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: glance/openstack/common/service.py:164
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: glance/openstack/common/service.py:200
msgid "Forking too fast, sleeping"
msgstr ""

#: glance/openstack/common/service.py:223
msgid "Unhandled exception"
msgstr ""

#: glance/openstack/common/service.py:230
#, python-format
msgid "Started child %d"
msgstr ""

#: glance/openstack/common/service.py:257
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: glance/openstack/common/service.py:261
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: glance/openstack/common/service.py:265
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: glance/openstack/common/service.py:293
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: glance/openstack/common/service.py:304
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: glance/openstack/common/strutils.py:72
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: glance/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:219
msgid "version should be an integer"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:251
msgid "Upgrade DB using Essex release first."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:553
msgid "DB exception wrapped."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:616
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:696
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:196
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:202
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:282
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:303
msgid "Unsupported id columns type"
msgstr ""

#: glance/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr "%s not in valid priorities"

#: glance/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"

#: glance/openstack/common/notifier/api.py:171
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr "Failed to load notifier %s. These notifications will not be sent."

#: glance/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."

#: glance/openstack/common/notifier/rpc_notifier.py:45
#: glance/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr "Could not send notification to %(topic)s. Payload=%(message)s"

#: glance/quota/__init__.py:154
#, python-format
msgid "Cleaning up %s after exceeding the quota."
msgstr ""

#: glance/registry/__init__.py:27
msgid "Address to find the registry server."
msgstr "Address to find the registry server."

#: glance/registry/__init__.py:29
msgid "Port the registry server is listening on."
msgstr "Port the registry server is listening on."

#: glance/registry/api/v1/images.py:109
msgid "Invalid marker. Image could not be found."
msgstr "Invalid marker. Image could not be found."

#: glance/registry/api/v1/images.py:141
msgid "Returning image list"
msgstr "Returning image list"

#: glance/registry/api/v1/images.py:159
msgid "Returning detailed image list"
msgstr "Returning detailed image list"

#: glance/registry/api/v1/images.py:210
msgid "Unrecognized changes-since value"
msgstr "Unrecognized changes-since value"

#: glance/registry/api/v1/images.py:215
msgid "protected must be True, or False"
msgstr "protected must be True, or False"

#: glance/registry/api/v1/images.py:252
msgid "Invalid marker format"
msgstr "Invalid marker format"

#: glance/registry/api/v1/images.py:262
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Unsupported sort_key. Acceptable values: %s"

#: glance/registry/api/v1/images.py:271
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Unsupported sort_dir. Acceptable values: %s"

#: glance/registry/api/v1/images.py:297
msgid "is_public must be None, True, or False"
msgstr "is_public must be None, True, or False"

#: glance/registry/api/v1/images.py:313
#, python-format
msgid "Successfully retrieved image %(id)s"
msgstr "Successfully retrieved image %(id)s"

#: glance/registry/api/v1/images.py:316 glance/registry/api/v1/images.py:354
#: glance/registry/api/v1/images.py:445 glance/registry/api/v1/members.py:47
#: glance/registry/api/v1/members.py:81 glance/registry/api/v1/members.py:194
#: glance/registry/api/v1/members.py:254
#, python-format
msgid "Image %(id)s not found"
msgstr "Image %(id)s not found"

#: glance/registry/api/v1/images.py:322 glance/registry/api/v1/images.py:350
#: glance/registry/api/v1/images.py:457 glance/registry/api/v1/members.py:53
#: glance/registry/api/v1/members.py:87 glance/registry/api/v1/members.py:200
#: glance/registry/api/v1/members.py:260
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr "Access denied to image %(id)s but returning 'not found'"

#: glance/registry/api/v1/images.py:340
#, python-format
msgid "Successfully deleted image %(id)s"
msgstr "Successfully deleted image %(id)s"

#: glance/registry/api/v1/images.py:344
#, python-format
msgid "Delete denied for public image %(id)s"
msgstr "Delete denied for public image %(id)s"

#: glance/registry/api/v1/images.py:380
#, python-format
msgid "Rejecting image creation request for invalid image id '%(bad_id)s'"
msgstr "Rejecting image creation request for invalid image id '%(bad_id)s'"

#: glance/registry/api/v1/images.py:383
msgid "Invalid image id format"
msgstr "Invalid image id format"

#: glance/registry/api/v1/images.py:392
#, python-format
msgid "Successfully created image %(id)s"
msgstr "Successfully created image %(id)s"

#: glance/registry/api/v1/images.py:396
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Image with identifier %s already exists!"

#: glance/registry/api/v1/images.py:400
#, python-format
msgid "Failed to add image metadata. Got error: %(e)s"
msgstr "Failed to add image metadata. Got error: %(e)s"

#: glance/registry/api/v1/images.py:426
#, python-format
msgid "Updating image %(id)s with metadata: %(image_data)r"
msgstr "Updating image %(id)s with metadata: %(image_data)r"

#: glance/registry/api/v1/images.py:436
#, python-format
msgid "Updating metadata for image %(id)s"
msgstr "Updating metadata for image %(id)s"

#: glance/registry/api/v1/images.py:451
#, python-format
msgid "Update denied for public image %(id)s"
msgstr "Update denied for public image %(id)s"

#: glance/registry/api/v1/members.py:58
#, python-format
msgid "Returning member list for image %(id)s"
msgstr "Returning member list for image %(id)s"

#: glance/registry/api/v1/members.py:93 glance/registry/api/v1/members.py:206
#: glance/registry/api/v1/members.py:266
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr "User lacks permission to share image %(id)s"

#: glance/registry/api/v1/members.py:95 glance/registry/api/v1/members.py:208
#: glance/registry/api/v1/members.py:268
msgid "No permission to share that image"
msgstr "No permission to share that image"

#: glance/registry/api/v1/members.py:103 glance/registry/api/v1/members.py:119
#: glance/registry/api/v1/members.py:218
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr "Invalid membership association specified for image %(id)s"

#: glance/registry/api/v1/members.py:106 glance/registry/api/v1/members.py:122
#: glance/registry/api/v1/members.py:221
#, python-format
msgid "Invalid membership association: %s"
msgstr "Invalid membership association: %s"

#: glance/registry/api/v1/members.py:170
#, python-format
msgid "Successfully updated memberships for image %(id)s"
msgstr "Successfully updated memberships for image %(id)s"

#: glance/registry/api/v1/members.py:239
#, python-format
msgid "Successfully updated a membership for image %(id)s"
msgstr "Successfully updated a membership for image %(id)s"

#: glance/registry/api/v1/members.py:278
#, python-format
msgid "%(id)s is not a member of image %(image_id)s"
msgstr "%(id)s is not a member of image %(image_id)s"

#: glance/registry/api/v1/members.py:281 glance/registry/api/v1/members.py:298
msgid "Membership could not be found."
msgstr "Membership could not be found."

#: glance/registry/api/v1/members.py:285
#, python-format
msgid "Successfully deleted a membership from image %(id)s"
msgstr "Successfully deleted a membership from image %(id)s"

#: glance/registry/api/v1/members.py:296
#, python-format
msgid "Member %(id)s not found"
msgstr "Member %(id)s not found"

#: glance/registry/api/v1/members.py:301
#, python-format
msgid "Returning list of images shared with member %(id)s"
msgstr "Returning list of images shared with member %(id)s"

#: glance/registry/api/v2/rpc.py:44
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:22
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""
"The protocol to use for communication with the registry server.  Either "
"http or https."

#: glance/registry/client/__init__.py:25
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr "The path to the key file to use in SSL connections to the registry server."

#: glance/registry/client/__init__.py:28
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""
"The path to the cert file to use in SSL connections to the registry "
"server."

#: glance/registry/client/__init__.py:31
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."

#: glance/registry/client/__init__.py:34
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."

#: glance/registry/client/__init__.py:38
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."

#: glance/registry/client/__init__.py:45
msgid ""
"Whether to pass through the user token when making requests to the "
"registry."
msgstr ""

#: glance/registry/client/__init__.py:48
msgid "The administrators user name."
msgstr "The administrators user name."

#: glance/registry/client/__init__.py:50
msgid "The administrators password."
msgstr "The administrators password."

#: glance/registry/client/__init__.py:52
msgid "The tenant name of the adminstrative user."
msgstr "The tenant name of the adminstrative user."

#: glance/registry/client/__init__.py:54
msgid "The URL to the keystone service."
msgstr "The URL to the keystone service."

#: glance/registry/client/__init__.py:56
msgid "The strategy to use for authentication."
msgstr "The strategy to use for authentication."

#: glance/registry/client/__init__.py:58
msgid "The region for the authentication service."
msgstr "The region for the authentication service."

#: glance/registry/client/v1/api.py:35
msgid ""
"Whether to pass through headers containing user and tenant information "
"when making requests to the registry. This allows the registry to use the"
" context middleware without the keystoneclients' auth_token middleware, "
"removing calls to the keystone auth service. It is recommended that when "
"using this option, secure communication between glance api and glance "
"registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/registry/client/v1/api.py:80 glance/registry/client/v2/api.py:62
msgid "Configuration option was not valid"
msgstr "Configuration option was not valid"

#: glance/registry/client/v1/api.py:84 glance/registry/client/v2/api.py:66
msgid "Could not find required configuration option"
msgstr "Could not find required configuration option"

#: glance/registry/client/v1/api.py:161
msgid "Adding image metadata..."
msgstr "Adding image metadata..."

#: glance/registry/client/v1/api.py:168
#, python-format
msgid "Updating image metadata for image %s..."
msgstr "Updating image metadata for image %s..."

#: glance/registry/client/v1/api.py:174
#, python-format
msgid "Deleting image metadata for image %s..."
msgstr "Deleting image metadata for image %s..."

#: glance/registry/client/v1/client.py:113
#, python-format
msgid ""
"Registry request %(method)s %(action)s HTTP %(status)s request id "
"%(request_id)s"
msgstr ""
"Registry request %(method)s %(action)s HTTP %(status)s request id "
"%(request_id)s"

#: glance/registry/client/v1/client.py:121
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr "Registry client request %(method)s %(action)s raised %(exc_name)s"

#: glance/store/__init__.py:48
msgid ""
"List of which store classes and store class locations are currently known"
" to glance at startup."
msgstr ""
"List of which store classes and store class locations are currently known"
" to glance at startup."

#: glance/store/__init__.py:51
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."
msgstr ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."

#: glance/store/__init__.py:56 glance/store/scrubber.py:40
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete. Make sure this is set in glance-api.conf and glance-scrubber.conf"
msgstr ""

#: glance/store/__init__.py:61
msgid "Turn on/off delayed delete."
msgstr "Turn on/off delayed delete."

#: glance/store/__init__.py:63 glance/store/scrubber.py:45
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "The amount of time in seconds to delay before performing a delete."

#: glance/store/__init__.py:275
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/store/__init__.py:281
#, python-format
msgid "Failed to delete image %s from store (%s)"
msgstr ""

#: glance/store/__init__.py:314
#, python-format
msgid ""
"The image metadata key %s has an invalid type of %s.  Only dict, list, "
"and unicode are supported."
msgstr ""

#: glance/store/__init__.py:336
#, python-format
msgid ""
"The storage driver %s returned invalid metadata %sThis must be a "
"dictionary type"
msgstr ""

#: glance/store/__init__.py:344
#, python-format
msgid "A bad metadata structure was returned from the %s storage driver: %s.  %s."
msgstr ""

#: glance/store/__init__.py:369
msgid "Skipping store.set_acls... not implemented."
msgstr "Skipping store.set_acls... not implemented."

#: glance/store/__init__.py:419
#, python-format
msgid "Invalid location: %s"
msgstr ""

#: glance/store/__init__.py:591
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/store/__init__.py:661
#, python-format
msgid "Get image %(id)s data from %(loc)s failed: %(err)s."
msgstr ""

#: glance/store/__init__.py:666
#, python-format
msgid "Glance tried all locations to get data for image %s but all have failed."
msgstr ""

#: glance/store/base.py:38 glance/tests/unit/test_store_base.py:46
#, python-format
msgid "Caught '%(exception)s' exception."
msgstr ""

#: glance/store/base.py:59
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr "Failed to configure store correctly: %s Disabling add method."

#: glance/store/cinder.py:91
#, python-format
msgid "Cinderclient connection created using URL: %s"
msgstr ""

#: glance/store/cinder.py:121
msgid "URI must start with cinder://"
msgstr ""

#: glance/store/cinder.py:129
#, python-format
msgid "URI contains invalid volume ID: %s"
msgstr ""

#: glance/store/cinder.py:152
msgid "Cinder storage requires a context."
msgstr ""

#: glance/store/cinder.py:156
msgid "Cinder storage requires a service catalog."
msgstr ""

#: glance/store/cinder.py:178
#, python-format
msgid "Failed to get image size due to volume can not be found: %s"
msgstr ""

#: glance/store/cinder.py:183
#, python-format
msgid "Failed to get image size due to internal error: %s"
msgstr ""

#: glance/store/filesystem.py:41
msgid "Directory to which the Filesystem backend store writes images."
msgstr "Directory to which the Filesystem backend store writes images."

#: glance/store/filesystem.py:44
msgid ""
"The path to a file which contains the metadata to be returned with any "
"location associated with this store.  The file must contain a valid JSON "
"dict."
msgstr ""

#: glance/store/filesystem.py:75
#, python-format
msgid "No path specified in URI: %s"
msgstr "No path specified in URI: %s"

#: glance/store/filesystem.py:128
#, python-format
msgid "Could not find %s in configuration options."
msgstr "Could not find %s in configuration options."

#: glance/store/filesystem.py:135
#, python-format
msgid "Directory to write image files does not exist (%s). Creating."
msgstr "Directory to write image files does not exist (%s). Creating."

#: glance/store/filesystem.py:146
#, python-format
msgid "Unable to create datadir: %s"
msgstr "Unable to create datadir: %s"

#: glance/store/filesystem.py:156
#, python-format
msgid "Image file %s not found"
msgstr "Image file %s not found"

#: glance/store/filesystem.py:171
#, python-format
msgid ""
"The JSON in the metadata file %s could not be used: %s  An empty "
"dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:177
#, python-format
msgid ""
"The path for the metadata file %s could not be opened: %s  An empty "
"dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:183
#, python-format
msgid ""
"An error occured processing the storage systems meta data file: %s.  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:199
#, python-format
msgid "Found image at %s. Returning in ChunkedFile."
msgstr "Found image at %s. Returning in ChunkedFile."

#: glance/store/filesystem.py:214
#, python-format
msgid "Found image at %s."
msgstr "Found image at %s."

#: glance/store/filesystem.py:233
#, python-format
msgid "Deleting image at %(fn)s"
msgstr "Deleting image at %(fn)s"

#: glance/store/filesystem.py:236
#, python-format
msgid "You cannot delete file %s"
msgstr "You cannot delete file %s"

#: glance/store/filesystem.py:238
#, python-format
msgid "Image file %s does not exist"
msgstr "Image file %s does not exist"

#: glance/store/filesystem.py:264
#, python-format
msgid "Image file %s already exists!"
msgstr "Image file %s already exists!"

#: glance/store/filesystem.py:290
#, python-format
msgid ""
"Wrote %(bytes_written)d bytes to %(filepath)s with checksum "
"%(checksum_hex)s"
msgstr ""
"Wrote %(bytes_written)d bytes to %(filepath)s with checksum "
"%(checksum_hex)s"

#: glance/store/filesystem.py:302
#, python-format
msgid "Unable to remove partial image data for image %s: %s"
msgstr "Unable to remove partial image data for image %s: %s"

#: glance/store/gridfs.py:100
msgid "Missing dependecies: pymongo"
msgstr ""

#: glance/store/gridfs.py:116 glance/store/s3.py:254 glance/store/swift.py:318
#, python-format
msgid "Could not find %(param)s in configuration options."
msgstr "Could not find %(param)s in configuration options."

#: glance/store/gridfs.py:160
#, python-format
msgid "Could not find %s image in GridFS"
msgstr ""

#: glance/store/gridfs.py:183
#, python-format
msgid "GridFS already has an image at location %s"
msgstr ""

#: glance/store/gridfs.py:186
#, python-format
msgid "Adding a new image to GridFS with id %s and size %s"
msgstr ""

#: glance/store/gridfs.py:198
#, python-format
msgid "Uploaded image %s, md5 %s, length %s to GridFS"
msgstr ""

#: glance/store/http.py:82
#, python-format
msgid "Credentials '%s' not well-formatted."
msgstr "Credentials '%s' not well-formatted."

#: glance/store/http.py:89
msgid "No address specified in HTTP URL"
msgstr "No address specified in HTTP URL"

#: glance/store/http.py:164
#, python-format
msgid "HTTP URL returned a %s status code."
msgstr "HTTP URL returned a %s status code."

#: glance/store/http.py:170
msgid "The HTTP URL attempted to redirect with an invalid status code."
msgstr "The HTTP URL attempted to redirect with an invalid status code."

#: glance/store/rbd.py:55 glance/store/sheepdog.py:44
msgid ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."
msgstr ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."

#: glance/store/rbd.py:59
msgid "RADOS pool in which images are stored."
msgstr "RADOS pool in which images are stored."

#: glance/store/rbd.py:61
msgid "RADOS user to authenticate as (only applicable if using cephx.)"
msgstr "RADOS user to authenticate as (only applicable if using cephx.)"

#: glance/store/rbd.py:64
msgid "Ceph configuration file path."
msgstr "Ceph configuration file path."

#: glance/store/rbd.py:106
msgid "URI must start with rbd://"
msgstr "URI must start with rbd://"

#: glance/store/rbd.py:107 glance/store/rbd.py:116 glance/store/rbd.py:129
#: glance/store/rbd.py:135
#, python-format
msgid "Invalid URI: %(uri)s: %(reason)s"
msgstr "Invalid URI: %(uri)s: %(reason)s"

#: glance/store/rbd.py:115
msgid "URI contains non-ascii characters"
msgstr "URI contains non-ascii characters"

#: glance/store/rbd.py:128
msgid "URI must have exactly 1 or 4 components"
msgstr "URI must have exactly 1 or 4 components"

#: glance/store/rbd.py:134
msgid "URI cannot contain empty components"
msgstr "URI cannot contain empty components"

#: glance/store/rbd.py:170 glance/store/rbd.py:234 glance/store/rbd.py:294
#, python-format
msgid "RBD image %s does not exist"
msgstr "RBD image %s does not exist"

#: glance/store/rbd.py:197 glance/store/sheepdog.py:199
#: glance/store/sheepdog.py:207
#, python-format
msgid "Error in store configuration: %s"
msgstr "Error in store configuration: %s"

#: glance/store/rbd.py:281
#, python-format
msgid "snapshot %(image)s@%(snap)s could not be unprotected because it is in use"
msgstr ""

#: glance/store/rbd.py:296
#, python-format
msgid "image %s could not be removed because it is in use"
msgstr ""

#: glance/store/rbd.py:327
msgid ""
"since image size is zero we will be doing resize-before-write for each "
"chunk which will be considerably slower than normal"
msgstr ""

#: glance/store/rbd.py:336
#, python-format
msgid "RBD image %s already exists"
msgstr "RBD image %s already exists"

#: glance/store/rbd.py:349
#, python-format
msgid "resizing image to %s KiB"
msgstr ""

#: glance/store/rbd.py:352
#, python-format
msgid "writing chunk at offset %s"
msgstr ""

#: glance/store/s3.py:39
msgid "The host where the S3 server is listening."
msgstr "The host where the S3 server is listening."

#: glance/store/s3.py:41
msgid "The S3 query token access key."
msgstr "The S3 query token access key."

#: glance/store/s3.py:43
msgid "The S3 query token secret key."
msgstr "The S3 query token secret key."

#: glance/store/s3.py:45
msgid "The S3 bucket to be used to store the Glance data."
msgstr "The S3 bucket to be used to store the Glance data."

#: glance/store/s3.py:47
msgid ""
"The local directory where uploads will be staged before they are "
"transfered into S3."
msgstr ""
"The local directory where uploads will be staged before they are "
"transfered into S3."

#: glance/store/s3.py:50
msgid ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."
msgstr ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."

#: glance/store/s3.py:54
msgid ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."
msgstr ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."

#: glance/store/s3.py:117
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"

#: glance/store/s3.py:125
#, python-format
msgid "Invalid store uri: %s"
msgstr ""

#: glance/store/s3.py:151
#, python-format
msgid "Badly formed S3 credentials %s"
msgstr "Badly formed S3 credentials %s"

#: glance/store/s3.py:164
msgid "Badly formed S3 URI. Missing s3 service URL."
msgstr "Badly formed S3 URI. Missing s3 service URL."

#: glance/store/s3.py:309
#, python-format
msgid ""
"Retrieved image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Retrieved image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:369
#, python-format
msgid "S3 already has an image at location %s"
msgstr "S3 already has an image at location %s"

#: glance/store/s3.py:373
#, python-format
msgid ""
"Adding image object to S3 using (s3_host=%(s3_host)s, "
"access_key=%(access_key)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Adding image object to S3 using (s3_host=%(s3_host)s, "
"access_key=%(access_key)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:395
#, python-format
msgid "Writing request body file to temporary file for %s"
msgstr "Writing request body file to temporary file for %s"

#: glance/store/s3.py:407
#, python-format
msgid "Uploading temporary file to S3 for %s"
msgstr "Uploading temporary file to S3 for %s"

#: glance/store/s3.py:416
#, python-format
msgid ""
"Wrote %(size)d bytes to S3 key named %(obj_name)s with checksum "
"%(checksum_hex)s"
msgstr ""
"Wrote %(size)d bytes to S3 key named %(obj_name)s with checksum "
"%(checksum_hex)s"

#: glance/store/s3.py:444
#, python-format
msgid ""
"Deleting image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""
"Deleting image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"

#: glance/store/s3.py:466
#, python-format
msgid "Could not find bucket with ID %s"
msgstr ""

#: glance/store/s3.py:507
#, python-format
msgid ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"
msgstr ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"

#: glance/store/s3.py:511
#, python-format
msgid ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."
msgstr ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."

#: glance/store/s3.py:530
#, python-format
msgid "Could not find key %(obj)s in bucket %(bucket)s"
msgstr "Could not find key %(obj)s in bucket %(bucket)s"

#: glance/store/scrubber.py:48
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."

#: glance/store/scrubber.py:53
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."

#: glance/store/scrubber.py:136
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/store/scrubber.py:160
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/store/scrubber.py:211
#, python-format
msgid "%s directory does not exist."
msgstr ""

#: glance/store/scrubber.py:357
#, python-format
msgid "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"
msgstr "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"

#: glance/store/scrubber.py:371
msgid "Daemon Shutdown on KeyboardInterrupt"
msgstr "Daemon Shutdown on KeyboardInterrupt"

#: glance/store/scrubber.py:375
msgid "Running application"
msgstr "Running application"

#: glance/store/scrubber.py:378
#, python-format
msgid "Next run scheduled in %s seconds"
msgstr "Next run scheduled in %s seconds"

#: glance/store/scrubber.py:383
#, python-format
msgid "Initializing scrubber with configuration: %s"
msgstr ""

#: glance/store/scrubber.py:407
#, python-format
msgid "Can not %s scrub jobs from queue."
msgstr ""

#: glance/store/scrubber.py:431
#, python-format
msgid "Scrubbing image %(id)s from %(count)d locations."
msgstr ""

#: glance/store/scrubber.py:446
#, python-format
msgid "Deleting URI from image %(image_id)s."
msgstr ""

#: glance/store/scrubber.py:459
#, python-format
msgid "Failed to delete URI from image %(image_id)s"
msgstr ""

#: glance/store/scrubber.py:471
#, python-format
msgid "%s file is not exists."
msgstr ""

#: glance/store/scrubber.py:476
#, python-format
msgid "%s file contains conflicting cleanup timestamp."
msgstr ""

#: glance/store/scrubber.py:495
#, python-format
msgid "%s file can not be created."
msgstr ""

#: glance/store/scrubber.py:509
#, python-format
msgid "Getting images deleted before %s"
msgstr "Getting images deleted before %s"

#: glance/store/sheepdog.py:48
msgid "Port of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:50
msgid "IP address of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:227 glance/store/sheepdog.py:246
#: glance/store/sheepdog.py:307
#, python-format
msgid "Sheepdog image %s does not exist"
msgstr ""

#: glance/store/sheepdog.py:268
#, python-format
msgid "Sheepdog image %s already exists"
msgstr ""

#: glance/store/swift.py:52
msgid "Whether to use ServiceNET to communicate with the Swift storage servers."
msgstr "Whether to use ServiceNET to communicate with the Swift storage servers."

#: glance/store/swift.py:55
msgid "The address where the Swift authentication service is listening."
msgstr "The address where the Swift authentication service is listening."

#: glance/store/swift.py:58
msgid "The user to authenticate against the Swift authentication service"
msgstr "The user to authenticate against the Swift authentication service"

#: glance/store/swift.py:61
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service."
msgstr ""
"Auth key for the user authenticating against the Swift authentication "
"service."

#: glance/store/swift.py:64
msgid ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace"
msgstr ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace"

#: glance/store/swift.py:68
msgid ""
"If True, swiftclient won't check for a valid SSL certificate when "
"authenticating."
msgstr ""

#: glance/store/swift.py:71
msgid ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."
msgstr ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."

#: glance/store/swift.py:75
msgid ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."
msgstr ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."

#: glance/store/swift.py:80
msgid ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."
msgstr ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."

#: glance/store/swift.py:85
msgid ""
"Container within the account that the account should use for storing "
"images in Swift."
msgstr ""
"Container within the account that the account should use for storing "
"images in Swift."

#: glance/store/swift.py:89
msgid ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift"
msgstr ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift"

#: glance/store/swift.py:93
msgid ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."
msgstr ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."

#: glance/store/swift.py:96
msgid ""
"A boolean value that determines if we create the container if it does not"
" exist."
msgstr ""
"A boolean value that determines if we create the container if it does not"
" exist."

#: glance/store/swift.py:99
msgid ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."
msgstr ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."

#: glance/store/swift.py:103
msgid ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."
msgstr ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."

#: glance/store/swift.py:107
msgid ""
"If set to False, disables SSL layer compression of https swift requests. "
"Setting to False may improve performance for images which are already in "
"a compressed format, eg qcow2."
msgstr ""

#: glance/store/swift.py:178
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/store/swift.py:184
#, python-format
msgid "Invalid store URI: %(reason)s"
msgstr "Invalid store URI: %(reason)s"

#: glance/store/swift.py:228
msgid "Badly formed Swift URI."
msgstr "Badly formed Swift URI."

#: glance/store/swift.py:289 glance/store/swift.py:491
#: glance/store/swift.py:652
msgid "Swift could not find image at URI."
msgstr "Swift could not find image at URI."

#: glance/store/swift.py:327
#, python-format
msgid "Deleting chunk %s"
msgstr "Deleting chunk %s"

#: glance/store/swift.py:331
#, python-format
msgid "Failed to delete orphaned chunk %s/%s"
msgstr "Failed to delete orphaned chunk %s/%s"

#: glance/store/swift.py:341
#, python-format
msgid "Adding image object '%(obj_name)s' to Swift"
msgstr "Adding image object '%(obj_name)s' to Swift"

#: glance/store/swift.py:361
msgid "Cannot determine image size. Adding as a segmented object to Swift."
msgstr "Cannot determine image size. Adding as a segmented object to Swift."

#: glance/store/swift.py:390
msgid "Error during chunked upload to backend, deleting stale chunks"
msgstr ""

#: glance/store/swift.py:397
#, python-format
msgid ""
"Wrote chunk %(chunk_name)s (%(chunk_id)d/%(total_chunks)s) of length "
"%(bytes_read)d to Swift returning MD5 of content: %(chunk_etag)s"
msgstr ""
"Wrote chunk %(chunk_name)s (%(chunk_id)d/%(total_chunks)s) of length "
"%(bytes_read)d to Swift returning MD5 of content: %(chunk_etag)s"

#: glance/store/swift.py:411
msgid "Deleting final zero-length chunk"
msgstr "Deleting final zero-length chunk"

#: glance/store/swift.py:448
msgid "Swift already has an image at this location"
msgstr "Swift already has an image at this location"

#: glance/store/swift.py:450
#, python-format
msgid ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"

#: glance/store/swift.py:512
#, python-format
msgid ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"

#: glance/store/swift.py:516
#, python-format
msgid ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."
msgstr ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."

#: glance/store/swift.py:560
msgid "Location is missing user:password information."
msgstr "Location is missing user:password information."

#: glance/store/swift.py:572
#, python-format
msgid "Badly formed tenant:user '%(user)s' in Swift URI"
msgstr "Badly formed tenant:user '%(user)s' in Swift URI"

#: glance/store/swift.py:599
msgid "Multi-tenant Swift storage requires a context."
msgstr "Multi-tenant Swift storage requires a context."

#: glance/store/swift.py:603
msgid "Multi-tenant Swift storage requires a service catalog."
msgstr "Multi-tenant Swift storage requires a service catalog."

#: glance/tests/unit/test_migrations.py:833
#, python-format
msgid "location: %s data lost"
msgstr "location: %s data lost"

#~ msgid "Failed to upload image"
#~ msgstr "Failed to upload image"

#~ msgid "Unable to kill image %(id)s: %(exc)s"
#~ msgstr "Unable to kill image %(id)s: %(exc)s"

#~ msgid "Forbidden to delete a deleted image."
#~ msgstr "Forbidden to delete a deleted image."

#~ msgid "Pointer `%s` contains more than one \"/\"."
#~ msgstr "Pointer `%s` contains more than one \"/\"."

#~ msgid "Status of the image"
#~ msgstr "Status of the image"

#~ msgid "md5 hash of image contents."
#~ msgstr "md5 hash of image contents."

#~ msgid "Size of image file in bytes"
#~ msgstr "Size of image file in bytes"

#~ msgid "Date and time of image registration"
#~ msgstr "Date and time of image registration"

#~ msgid "Date and time of the last image modification"
#~ msgstr "Date and time of the last image modification"

#~ msgid "URL to access the image file kept in external store"
#~ msgstr "URL to access the image file kept in external store"

#~ msgid "eventlet 'poll' hub is not available on this platform"
#~ msgstr "eventlet 'poll' hub is not available on this platform"

#~ msgid "Max serialization depth exceeded on object: %d %s"
#~ msgstr "Max serialization depth exceeded on object: %d %s"

#~ msgid ""
#~ msgstr ""

#~ msgid "Image id %(image_id)s already queued for delete"
#~ msgstr "Image id %(image_id)s already queued for delete"

#~ msgid "image %s could not be removedbecause it is in use"
#~ msgstr "image %s could not be removedbecause it is in use"

#~ msgid "Initializing scrubber with conf: %s"
#~ msgstr "Initializing scrubber with conf: %s"

#~ msgid "%s does not exist"
#~ msgstr "%s does not exist"

#~ msgid "Deleting %s images"
#~ msgstr "Deleting %s images"

#~ msgid "Deleting %(uri)s"
#~ msgstr "Deleting %(uri)s"

#~ msgid "Failed to delete image from store (%(id)s)."
#~ msgstr "Failed to delete image from store (%(id)s)."

#~ msgid "Image not found in store (%(id)s)."
#~ msgstr "Image not found in store (%(id)s)."

#~ msgid "Deploy the v1 OpenStack Images API. "
#~ msgstr "Deploy the v1 OpenStack Images API. "

#~ msgid "Deploy the v2 OpenStack Images API. "
#~ msgstr "Deploy the v2 OpenStack Images API. "

#~ msgid "Invalid store uri %(uri)s: %(reason)s"
#~ msgstr "Invalid store uri %(uri)s: %(reason)s"

#~ msgid "Failed to delete image in store at URI: %s"
#~ msgstr "Failed to delete image in store at URI: %s"

#~ msgid "Failed to delete image at %s from store (%s)"
#~ msgstr "Failed to delete image at %s from store (%s)"

#~ msgid "snapshot %s@%s could not be unprotected because it is in use"
#~ msgstr "snapshot %s@%s could not be unprotected because it is in use"

#~ msgid "Deleting %(uri)s from image %(image_id)s."
#~ msgstr ""

#~ msgid "Failed to delete image %(image_id)s from %(uri)s."
#~ msgstr ""

#~ msgid ""
#~ "Whether to include the backend image "
#~ "storage location in image properties. "
#~ "Revealing storage location can be a "
#~ "security risk, so use this setting "
#~ "with caution!"
#~ msgstr ""
#~ "Whether to include the backend image "
#~ "storage location in image properties. "
#~ "Revealing storage location can be a "
#~ "security risk, so use this setting "
#~ "with caution!"

#~ msgid "Invalid syslog facility"
#~ msgstr "Invalid syslog facility"

#~ msgid "Could not find bucket with ID %(bucket_id)s"
#~ msgstr "Could not find bucket with ID %(bucket_id)s"

